### PR TITLE
(perf) Improve specificity of the activationEvents in this extension

### PR DESCRIPTION
**Pull request by jasonwilliams**
Previously this extension was using `*` which means it's competing with VSCode for startup-time. This isn't recommended especially as the extension isn't changing layout or UI.

This change still activates the extension but after the core UI has fully loaded. I've also added detection for cspell.json files which may kick it in a bit faster.

https://code.visualstudio.com/api/references/activation-events#Start-up
_To ensure a great user experience, please use this activation event in your extension only when no other activation events combination works in your use-case._

### CODE REVIEW

**Comment by Jason3S** [comment]
Thank you. 
I haven't looked at the activation event for years. Looks like some new ones were added. 

`onStartupFinished` might be all that is needed.

**Comment by Jason3S** [comment]
Thank you

**Comment by Jason3S** [comment]
Were you seeing a slow startup? It takes less than 100ms on my machine.

**Comment by jasonwilliams** [comment]
I can’t remember what it was at but when you have a few extensions it can quickly add up. And this extension doesn’t need to start straight away.

**Pull request merged**
